### ISSUE TITLE
Underscore conflict on Paris instance

### ISSUE THREAD

**Issue by mhzgitdev** [noxify/ServiceNow-GraphQL-Example#2] opened 2020-10-02 03:29 UTC
Hi there. I put your code on a Paris PDI recently, and just today I realized Studio would not launch. 
This happened because I added Underscore as a global script include available from all scopes. 
Turns out this was the third Underscore script include. 

There is already one in the Code Search app and one in the Studio app. On launch Studio immediately loads a Scripted REST Resource called "List All Applications" which depends on its own Underscore and hangs indefinitely.

To fix I just disabled the Underscore from your repo here, and I modified the calls in GraphQLExampleUtilities to use "sn_codesearch._" instead, which the system has available for "All Application Scopes." 
Not sure if this is the ideal solution but just letting you know if a user installs your Underscore  globally available like I did, Studio won't launch.

Possibly if user just puts your Underscore in a restricted scope they could safely load it. 
I'm just experimenting so adjusted mine to use that oob version.

**Comment by noxify** [comment] 2020-10-07 09:54
Hi,

thanks for reporting the issue.

I was able to reproduce it.

After opening the Studio ( in a new tab ) i have seen the following error messages:

![image](https://user-images.githubusercontent.com/521777/95314114-2e992280-0891-11eb-85a3-b80859a36b22.png)

Based on the log entries, it seems that the problem is based on a semi-good implementation in the Script REST Resource:
![image](https://user-images.githubusercontent.com/521777/95314478-a2d3c600-0891-11eb-88d1-18eb9f30055b.png)

Here the related log entry

```
java.lang.SecurityException: _ undefined, maybe missing global qualifier
Caused by error in sys_ws_operation.5261eef5771123005dbb4311a8106160.operation_script at line 1
```

anyway... After renaming the `global._` Script include to `global.underscore.js` and updating the `GraphQLExampleUtilities`, the Studio is working again.

I will close this issue for now - feel free to reopen it or creating a new one if I have missed something :)


Regards,
Marcus

**Closed by noxify** 2020-10-07 09:54 UTC
